config/routes.rb
Rails.application.routes.draw do
  get '/' => 'welcome#index', as: :index
  post '/' => 'welcome#create', as: :submit
  delete "/:id" => "welcome#destroy"
  patch "/:id" => "welcome#update"
  put "/:id" => "welcome#completion", as: :completion
  get "/search" => "welcome#search"
  get "/:id" => "welcome#edit",   as: :support
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/support.rb
class Support < ApplicationRecord
  after_initialize :set_defaults

  def self.search(search)
    where (["name ILIKE ? OR email ILIKE ? OR department ILIKE ? OR message ILIKE?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" ])
  end

  def humanize_completion
    completion == false ? "Not Done" : "Done"
  end

  private

  def set_defaults
    self.completion ||= false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @supports = Support.order(completion: :ASC, created_at: :DESC).page(params[:page_all]).per(7)

    # @search_results = @supports
    @search = Support.search(params[:search])
    @search_results = @search.order(completion: :ASC, created_at: :DESC).page(params[:page_search]).per(7)
  end

  def create
    support_params = params.require(:support).permit(:name,:email,:department,:message)
    @support = Support.create support_params
    if @support.save
      redirect_to index_path
    else
      render :new
    end
  end

  # def search
  #   @search_results = @supports
  #   @search = params[:search]
  #   @search_results = Support.where (["name ILIKE ? OR email ILIKE ? OR department ILIKE ? OR message ILIKE?", "%#{@search}%", "%#{@search}%", "%#{@search}%", "%#{@search}%" ])
  #   @search_results = @search_results.order(completion: :ASC, created_at: :DESC).page(params[:page]).per(7)
  #   redirect_to index_path
  # end

  def edit
    @support = Support.find params[:id]
  end

  def destroy
    @support = Support.find params[:id]
    @support.destroy
    redirect_to index_path
  end

  def update
        @support = Support.find params[:id]
        support_params = params.require(:support).permit(:name,:email,:department,:message)
        if @support.update support_params
          redirect_to index_path
        else
          render :edit
        end
  end

  def completion
    @support = Support.find params[:id]
    @support.completion == true ? @support.completion = false : @support.completion = true
    @support.save
    redirect_to index_path
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupporterApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/edit.html.erb
<div class='form'>
    <h1>Supporter</h1>
    <hr/>

    <%= form_for @support do |p| %>
    <%= p.label :name %>
    <%= p.text_field :name %>
    <br>
    <%= p.label :email %>
    <%= p.text_field :email %>
    <br>
    <%= p.label :department %>
    <span id='radio'>
        <%= p.radio_button :department, 'sales' %>
        <%= p.label 'Sales' %>
        <%= p.radio_button :department, 'marketing' %>
        <%= p.label 'Marketing' %>
        <%= p.radio_button :department, 'technical' %>
        <%= p.label 'Technical' %>
    </span>
    <br>

    <%= p.label :message %>
    <%= p.text_area :message %>
    <br/>
    <%= p.submit "Save" %>
<% end %>
</div>

<div class = 'edit_requests'>
    ID:  <%= @support.id %><br />
    Name:  <%= @support.name %><br />
    Department:  <%= @support.department %><br />
    Message:  <%= @support.message %><br />
    Completed?  <%= @support.completion %><br />
</div>

app/views/welcome/index.html.erb
<div class='form'>
    <h1>Supporter</h1>
    <hr/>

    <%= form_for :support do |p| %>
    <%= p.label :name %>
    <%= p.text_field :name %>
    <br>
    <%= p.label :email %>
    <%= p.text_field :email %>
    <br>
    <%= p.label :department %>
    <span id='radio'>
        <%= p.radio_button :department, 'sales' %>
        <%= p.label 'Sales' %>
        <%= p.radio_button :department, 'marketing' %>
        <%= p.label 'Marketing' %>
        <%= p.radio_button :department, 'technical' %>
        <%= p.label 'Technical' %>
    </span>

    <br>
    <%= p.label :message %>
    <%= p.text_area :message %>
    <br/>
    <%= p.submit "Save" %>
    <% end %>
</div>

<div class="requests">
    <h2>Support Requests</h2>
    <%= paginate @supports, param_name: 'page_all' %>
    <table>
        <tr>
            <td>Name</td>
            <td>Email</td>
            <td>Department</td>
            <td>Message</td>
            <td>Actions</td>
        </tr>
        <% @supports.each do |p| %>
        <tr>
            <td><%= p.name%></td>
            <td><%= p.email%></td>
            <td><%= p.department%></td>
            <td><%= p.message%></td>
            <td>
                <%= link_to "Edit", support_path(p) %>

                <%= link_to "Delete", support_path(p), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>

                <%= link_to p.humanize_completion, support_path(p), method: :put %>

            </span>
        </td>
    </tr>
    <% end %>
</table>


<h2>Search Support Requests</h2>

<%= paginate @search_results, param_name: 'page_search'  %>

<%= form_tag index_path, :method => "get" do %>
    <%= label_tag(:search, "Search for Support Ticket:") %>
    <%= text_field_tag(:search) %>
    <%= submit_tag("Search Tickets") %>
<% end %>
<table>
    <tr>
        <td>Name</td>
        <td>Email</td>
        <td>Department</td>
        <td>Message</td>
        <td>Actions</td>
    </tr>
    <% @search_results.each do |s| %>
    <tr>
        <td><%= s.name%></td>
        <td><%= s.email%></td>
        <td><%= s.department%></td>
        <td><%= s.message%></td>
        <td>
            <%= link_to "Edit", support_path(s) %>

            <%= link_to "Delete", support_path(s), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>

            <%= link_to s.humanize_completion, support_path(s) , method: :put %>

        </td>
    </tr>
    <% end %>

</div>